$('.owl-carousel3').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoplay:true,
    autoplayTimeout:8000,
    autoplayHoverPause:false,
    responsive:{
        0:{
            items:1
        },
       576:{
            items:2
        },
        992:{
            items:3
        }
    }
})
